name: frontend
description: Flutter frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth_2: ^5.0.1
  shared_preferences: ^2.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google.png
    - assets/icons/github.png
    - assets/icons/facebook.png